apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: ec-gateway-class
spec: 
  controllerName: example.com/gateway-controller
  description: "ECサイト用のgatewayClass"
  parametersRef:
    group: gateway.networking.k8s.io
    kind:  gatewayClassconfig
    name:  ec-gateway-config
    

